/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sonu
 */
import javax.swing.JOptionPane;
import java.lang.*;
import java.sql.*;
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RoomNum = new javax.swing.JTextField();
        CapacityOfRoom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AddVenue = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Busername = new javax.swing.JTextField();
        BlockButton = new javax.swing.JButton();
        UnBlockUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Add Venue");

        jLabel2.setText("New Room Number");

        jLabel3.setText("Capacity");

        AddVenue.setText("Add This Venue");
        AddVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVenueActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Block User");

        jLabel5.setText("Enter username");

        BlockButton.setText("Block");
        BlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockButtonActionPerformed(evt);
            }
        });

        UnBlockUser.setText("UnBlock");
        UnBlockUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnBlockUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CapacityOfRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Busername, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(AddVenue)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Logout)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BlockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(UnBlockUser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logout)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CapacityOfRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(AddVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(BlockButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(Busername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(UnBlockUser)))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVenueActionPerformed
        // TODO add your handling code here:
        int roomno=Integer.parseInt(RoomNum.getText());
        int capacity=Integer.parseInt(CapacityOfRoom.getText());
        try{
        Class.forName("com.mysql.jdbc.Driver");  
        String conarg="jdbc:mysql://";
        conarg+=Home.Saddress;
        conarg+=":3306/sonupmandal";
 //Connection con=DriverManager.getConnection("jdbc:mysql://localhost":3306/sonupmandal",Home.UserName,"");  
                Connection con=DriverManager.getConnection(conarg,Home.UserName,Home.Password);
      //  Connection con=DriverManager.getConnection("jdbc:mysql://Home.Sadress:3306/sonupmandal",Home.UserName,"");  
        Statement stmt=con.createStatement();
        String query="SELECT room from roomdetail";
        ResultSet rs=stmt.executeQuery(query);
        boolean dlag=false;
        while(rs.next())
        {
            if(rs.getInt(1)==roomno)
            {
                dlag=true;
                break;
            }
        }
        
        
        if(dlag)
           JOptionPane.showMessageDialog(null,"This room is already Added for Bookings");
        else
        {
           if((capacity==300||capacity==500||capacity==1000||capacity==2000||capacity==3000))
               {
                    query="INSERT INTO roomdetail VALUES ('"+roomno+"','"+capacity+"')";
                   int eq=stmt.executeUpdate(query);
            //   UserHome.Roomintable[roomno]=capacity;
             //  UserHome.maxroom=Math.max(UserHome.maxroom,roomno);
             //  System.out.println(UserHome.maxroom);
               JOptionPane.showMessageDialog(null,"Succesfully Added Venue");
                   
                    
           }
           else
               JOptionPane.showMessageDialog(null,"Enter Capacity in Proper Amount\n Proper Amounts are\n300 500 1000 2000 3000");
           
           
        }
        }catch(Exception e){System.out.println(e);}
        
    }//GEN-LAST:event_AddVenueActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
         Home h=new Home();
        this.dispose();
        h.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void BlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockButtonActionPerformed
        // TODO add your handling code here:
        try{
        String uname=Busername.getText();
        Class.forName("com.mysql.jdbc.Driver");
        String conarg="jdbc:mysql://";
        conarg+=Home.Saddress;
        conarg+=":3306/sonupmandal";
 //Connection con=DriverManager.getConnection("jdbc:mysql://localhost":3306/sonupmandal",Home.UserName,"");  
                Connection con=DriverManager.getConnection(conarg,Home.UserName,Home.Password);
        
     //   Connection con=DriverManager.getConnection("jdbc:mysql://Home.Sadress:3306/sonupmandal",Home.UserName,"");
        Statement stmt=con.createStatement();
        String query="";
        query="UPDATE users set status=1 where username='"+uname+"'";
        int t=stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(null, uname+" Blocked for upcoming events ");
        }catch(Exception e){System.out.println(e);}
        
    }//GEN-LAST:event_BlockButtonActionPerformed

    private void UnBlockUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnBlockUserActionPerformed
        // TODO add your handling code here:
        try{
        String uname=Busername.getText();
        Class.forName("com.mysql.jdbc.Driver");
        String conarg="jdbc:mysql://";
        conarg+=Home.Saddress;
        conarg+=":3306/sonupmandal";
 //Connection con=DriverManager.getConnection("jdbc:mysql://localhost":3306/sonupmandal",Home.UserName,"");  
                Connection con=DriverManager.getConnection(conarg,Home.UserName,Home.Password);
        
     //   Connection con=DriverManager.getConnection("jdbc:mysql://Home.Sadress:3306/sonupmandal",Home.UserName,"");
        Statement stmt=con.createStatement();
        String query="";
        query="UPDATE users set status=0 where username='"+uname+"'";
        int t=stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(null, uname+" UnBlocked for upcoming events ");
        }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_UnBlockUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVenue;
    private javax.swing.JButton BlockButton;
    private javax.swing.JTextField Busername;
    private javax.swing.JTextField CapacityOfRoom;
    private javax.swing.JButton Logout;
    private javax.swing.JTextField RoomNum;
    private javax.swing.JButton UnBlockUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
